## Library

In [1]:
import numpy as np
import pandas as pd

## Import Data

In [2]:
'''Import data : 
- Sumber = Superstore.csv
- Nama = Sample - Superstore
- Format = CSV
- Tujuan = Untuk menganalisa data tersebut
'''

data = pd.read_csv("Sample_Superstore.csv", encoding="latin1")

# Data Exploration

### Data diubah menjadi Data Frame

In [3]:
superstore = pd.DataFrame(data)
superstore

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

Dataset memiliki dimensi :

Jumlah Baris = 9994

Jumlah Kolom = 21

In [4]:
superstore.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 3.3 MB

In [5]:
superstore.describe().round(2)

        Row ID  Postal Code     Sales  Quantity  Discount   Profit
count  9994.00      9994.00   9994.00   9994.00   9994.00  9994.00
mean   4997.50     55190.38    229.86      3.79      0.16    28.66
std    2885.16     32063.69    623.25      2.23      0.21   234.26
min       1.00      1040.00      0.44      1.00      0.00 -6599.98
25%    2499.25     23223.00     17.28      2.00      0.00     1.73
50%    4997.50     56430.50     54.49      3.00      0.20     8.67
75%    7495.75     90008.00    209.94      5.00      0.20    29.36
max    9994.00     99301.00  22638.48     14.00      0.80  8399.98

In [6]:
superstore.describe(include="string")

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name
count,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994
unique,5009,1237,1334,4,793,793,3,1,531,49,4,1862,3,17,1850
top,CA-2017-100111,9/5/2016,12/16/2015,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,California,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope
freq,14,38,35,5968,37,37,5191,9994,915,2001,3203,19,6026,1523,48

In [7]:
superstore.duplicated().sum()

np.int64(0)

In [8]:
duplicate_persentase = superstore.duplicated().mean() * 100

print(f"Persentase duplicate: {duplicate_persentase:.2f}%")

Persentase duplicate: 0.00%

In [9]:
superstore_clean = pd.DataFrame({
    "data_missing": superstore.isna().sum(),
    "persentase": (superstore.isna().mean()*100).round(2)
})

superstore_clean = superstore_clean[superstore_clean["data_missing"]>0]
superstore_clean

Empty DataFrame
Columns: [data_missing, persentase]
Index: []

Tidak ada missing value pada data tersebut

# Data Preparation

## Data Cleaning

In [10]:
superstore_copy = superstore.copy()

### Inkonsistensi data

In [11]:
superstore_copy["Ship Mode"].unique()

<ArrowStringArray>
['Second Class', 'Standard Class', 'First Class', 'Same Day']
Length: 4, dtype: str

In [12]:
superstore_copy["Segment"].unique()

<ArrowStringArray>
['Consumer', 'Corporate', 'Home Office']
Length: 3, dtype: str

In [13]:
superstore_copy["Country"].unique()

<ArrowStringArray>
['United States']
Length: 1, dtype: str

In [14]:
superstore_copy["City"].unique()

<ArrowStringArray>
[        'Henderson',       'Los Angeles',   'Fort Lauderdale',
           'Concord',           'Seattle',        'Fort Worth',
           'Madison',       'West Jordan',     'San Francisco',
           'Fremont',
 ...
        'Hagerstown',       'East Orange', 'Arlington Heights',
            'Oswego',       'Coon Rapids',      'San Clemente',
   'San Luis Obispo',        'Springdale',              'Lodi',
             'Mason']
Length: 531, dtype: str

In [15]:
superstore_copy["Region"].unique()

<ArrowStringArray>
['South', 'West', 'Central', 'East']
Length: 4, dtype: str

In [16]:
superstore_copy["Category"].unique()

<ArrowStringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str

In [17]:
superstore_copy["Sub-Category"].unique()

<ArrowStringArray>
[  'Bookcases',      'Chairs',      'Labels',      'Tables',     'Storage',
 'Furnishings',         'Art',      'Phones',     'Binders',  'Appliances',
       'Paper', 'Accessories',   'Envelopes',   'Fasteners',    'Supplies',
    'Machines',     'Copiers']
Length: 17, dtype: str

In [18]:
superstore_copy["Product Name"].unique()

<ArrowStringArray>
[                               'Bush Somerset Collection Bookcase',
      'Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back',
        'Self-Adhesive Address Labels for Typewriters by Universal',
                    'Bretford CR4500 Series Slim Rectangular Table',
                                   'Eldon Fold 'N Roll Cart System',
 'Eldon Expressions Wood and Plastic Desk Accessories, Cherry Wood',
                                                       'Newell 322',
                                   'Mitel 5320 IP Phone VoIP phone',
             'DXL Angle-View Binders with Locking Rings by Samsill',
                                 'Belkin F5C206VTEL 6 Outlet Surge',
 ...
  'Self-Adhesive Address Labels for Typewriters with Dispenser Box',
             'Office Star - Task Chair with Contemporary Loop Arms',
                                              'Grip Seal Envelopes',
                              'Penpower WorldCard Pro Card Scanner',
                     'Sony 8GB Class 10 Micro SDHC R40 Memory Card',
                                  'RCA ViSYS 25425RE1 Corded phone',
                                     'Cisco 8961 IP Phone Charcoal',
                                      'Eureka Hand Vacuum, Bagless',
                                                            'LG G2',
           'Eldon Jumbo ProFile Portable File Boxes Graphite/Black']
Length: 1850, dtype: str

### Handling tipe data

In [19]:
superstore_copy["Order Date"] = pd.to_datetime(superstore_copy["Order Date"])
superstore_copy["Ship Date"] = pd.to_datetime(superstore_copy["Ship Date"])
superstore_copy["Postal Code"]=superstore_copy["Postal Code"].astype(str)
superstore_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   datetime64[us]
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   str
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(2), str(14)
memory usage: 3.2 MB

### Menangani outlier

In [20]:
kolom_outlier = superstore_copy.select_dtypes(include=["float64"]).columns

In [21]:
kolom_outlier

Index(['Sales', 'Discount', 'Profit'], dtype='str')

In [22]:
for i in kolom_outlier :
    Q1 = superstore_copy[i].quantile(0.25)
    Q3 = superstore_copy[i].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outlier = (superstore_copy[i] < lower) | (superstore_copy[i] > upper)
    jumlah_outlier = outlier.sum()
    persentase_outlier = jumlah_outlier/len(outlier) * 100
    print(f"Jumlah Outlier pada Kolom {i} : {jumlah_outlier}")
    print(f"Persentase Outlier pada Kolom {i} : {persentase_outlier}\n")

Jumlah Outlier pada Kolom Sales : 1167
Persentase Outlier pada Kolom Sales : 11.677006203722232

Jumlah Outlier pada Kolom Discount : 856
Persentase Outlier pada Kolom Discount : 8.56513908345007

Jumlah Outlier pada Kolom Profit : 1881
Persentase Outlier pada Kolom Profit : 18.8212927756654

In [24]:
#superstore_copy.to_csv("Superstore_copy.csv", index=False)

In [25]:
superstore_copy.to_csv(
    'Superstore_copy.csv',
    sep=';',
    index=False,
    encoding='utf-8-sig'
)